language: python
python:
  - "3.8"

addons:
  firefox: latest

before_script:
  - pip install -r requirements.txt

# safelist (indicate the only branches to check)
branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
